<script lang="ts">
  import Footer from '$lib/components/Footer.svelte';
  import Logo from '$lib/components/Logo.svelte';
</script>

<svelte:head>
  <title>Privacy — Deepmarks</title>
  <meta
    name="description"
    content="Deepmarks privacy policy. We don't collect user data. Private keys never leave your browser."
  />
</svelte:head>

<a href="/" class="back"><Logo size={20} flip /> back</a>

<header class="page-header">
  <h1>privacy</h1>
  <p class="lede">we don't collect user data. here's what that means in practice.</p>
</header>

<section class="body">
  <p class="updated">Last updated: 2026-04-28</p>

  <h2>the short version</h2>
  <p>
    deepmarks is a client for nostr — an open protocol where every piece of content is
    a signed event published to relays you choose. we do not run a database of users,
    we do not track your browsing, we do not sell or share data with advertisers, and
    we have no analytics or tracking pixels on this site or in the browser extension.
    your nostr private key (your nsec) is generated and stored in your own browser and
    never leaves it.
  </p>
  <p>
    everything below is the longer version of that same statement, written so a corporate
    app store reviewer or a curious user can verify the claim against our open-source code.
  </p>

  <h2>what data the website handles</h2>
  <ul>
    <li>
      <strong>nostr events you publish</strong> — when you save a bookmark, send a zap,
      or follow another user, deepmarks helps you sign and broadcast a nostr event to
      the relays you have configured. the event itself is public on those relays. we do
      not maintain a private copy of it; we read it back from nostr the same way any
      other client would.
    </li>
    <li>
      <strong>your nostr private key (nsec)</strong> — stored in your browser's
      <code>localStorage</code> (or, when you sign in via a browser-extension signer like
      alby / nos2x, never visible to us at all). it is never transmitted to our servers.
      our backend has no api endpoint that receives an nsec.
    </li>
    <li>
      <strong>archive payments</strong> — when you pay 500 sats to permanently archive
      a page, the lightning invoice is generated by our payment proxy and settled through
      the bitcoin lightning network. we record the invoice's payment hash so we can credit
      the archive job; we do not record the paying wallet, your ip, or any other
      identifier. lifetime upgrades go through btcpay server, which we self-host —
      same minimal record (payment hash + the npub being credited).
    </li>
    <li>
      <strong>archive snapshots</strong> — when you ask us to permanently archive a page,
      our archive worker fetches that page from the public web, optionally encrypts it
      with a key only your nsec can decrypt, and uploads it to blossom storage servers.
      the only thing we keep is the resulting blob hash so you can find it later.
    </li>
    <li>
      <strong>username claims</strong> — if you claim a short handle like
      <code>/u/jim</code>, we store the mapping between that handle and your npub so the
      url resolves. nothing else is attached to the record.
    </li>
  </ul>

  <h2>what we do not collect</h2>
  <ul>
    <li>no analytics, no tracking pixels, no third-party trackers, no advertising sdks</li>
    <li>no cookies that identify you (we use no cookies at all on the public site)</li>
    <li>no browsing history, no list of pages you visit, no behavioral profiles</li>
    <li>no email address unless you voluntarily give us one for support</li>
    <li>no ip-address logs beyond standard short-lived web-server access logs (rotated within days)</li>
    <li>no credit card or bank information (payments are bitcoin lightning, settled peer-to-peer)</li>
  </ul>

  <h2>the browser extension</h2>
  <p>
    the deepmarks browser extension follows the same model:
  </p>
  <ul>
    <li>
      page metadata (title and description tag) is read only at the moment you click
      "save", only on the tab you are actively viewing, and is sent only to the nostr
      relays you have configured.
    </li>
    <li>
      your nsec is stored in the extension's local storage, encrypted with a password
      you set. it is never transmitted off your device.
    </li>
    <li>
      the extension exposes a <code>window.nostr</code> provider (nip-07) so other
      websites can request signatures from your key. each request prompts you for
      approval before we sign anything.
    </li>
    <li>
      the extension does not load remote code. all javascript is bundled at build
      time and shipped inside the extension package; nothing is fetched and
      <code>eval()</code>'d at runtime.
    </li>
  </ul>

  <h2>third parties we touch</h2>
  <ul>
    <li>
      <strong>nostr relays</strong> — by default deepmarks talks to a handful of public
      relays (relay.deepmarks.org, relay.damus.io, nos.lol, relay.primal.net). you can
      change this list in settings. these relays receive the events you publish.
    </li>
    <li>
      <strong>blossom storage</strong> — page archives are uploaded to blossom.deepmarks.org
      (which we host) and mirrored to additional blossom servers for redundancy.
    </li>
    <li>
      <strong>bitcoin lightning</strong> — zaps and archive payments route through
      our own lightning node; lifetime upgrades route through our self-hosted btcpay server.
    </li>
  </ul>
  <p>
    we do not use google analytics, facebook pixel, hotjar, mixpanel, segment, or any
    similar product. we do not embed third-party fonts or scripts that report back. the
    site is served from our own infrastructure.
  </p>

  <h2>your control</h2>
  <ul>
    <li>
      <strong>delete your data</strong>: bookmarks live on nostr relays. to delete one,
      publish a nip-09 deletion event from any nostr client — relays that honor deletions
      will drop the original. deepmarks's "delete" button does this for you.
    </li>
    <li>
      <strong>leave deepmarks</strong>: there is no account to close. clear your browser's
      localStorage (or the extension's storage) and sign in elsewhere — your bookmarks
      keep working in any other nostr client because they live on nostr, not on us.
    </li>
    <li>
      <strong>read our code</strong>: the frontend, browser extension, archive worker,
      and payment proxy are all open source at
      <a href="https://github.com/ostermayer/deepmarks-public" target="_blank" rel="noreferrer">github.com/ostermayer/deepmarks-public</a>.
      you can verify every claim above by reading the code.
    </li>
  </ul>

  <h2>children</h2>
  <p>
    deepmarks is not directed at children under 13 and we do not knowingly collect data
    from anyone of any age — see above.
  </p>

  <h2>changes</h2>
  <p>
    if we change anything material on this page, we'll bump the "last updated" date at
    the top and, where it matters, surface the change in the app. the canonical version
    of this policy is whatever this url shows right now.
  </p>

  <h2>contact</h2>
  <p>
    questions, concerns, or a takedown request? email
    <a href="mailto:hello@deepmarks.org">hello@deepmarks.org</a>.
  </p>
</section>

<Footer />

<style>
  .back {
    display: inline-flex;
    align-items: center;
    gap: 8px;
    margin: 16px 24px;
    font-size: 13px;
    color: var(--muted);
    text-decoration: none;
  }
  .back:hover {
    color: var(--coral);
  }
  .page-header {
    text-align: center;
    padding: 32px 24px 24px;
    border-bottom: 1px solid var(--rule);
    margin: 0 auto;
    max-width: 680px;
  }
  .page-header h1 {
    font-family: 'Space Grotesk', Inter, sans-serif;
    font-size: 36px;
    color: var(--ink-deep);
    letter-spacing: -0.6px;
    margin: 0 0 8px;
    font-weight: 600;
  }
  .lede {
    color: var(--muted);
    font-size: 15px;
    margin: 0;
  }
  .body {
    max-width: 680px;
    margin: 0 auto;
    padding: 24px 24px 60px;
    color: var(--ink);
    line-height: 1.7;
    font-size: 15px;
  }
  .updated {
    color: var(--muted);
    font-size: 12px;
    margin: 0 0 24px;
    font-family: 'Courier New', monospace;
  }
  .body h2 {
    font-family: 'Space Grotesk', Inter, sans-serif;
    font-size: 13px;
    text-transform: uppercase;
    color: var(--muted);
    letter-spacing: 1.5px;
    margin: 32px 0 12px;
    padding-bottom: 6px;
    border-bottom: 1px solid var(--rule);
    font-weight: 600;
  }
  .body p {
    margin: 0 0 14px;
  }
  .body ul {
    margin: 0 0 18px;
    padding-left: 22px;
  }
  .body li {
    margin-bottom: 8px;
  }
  .body strong {
    color: var(--ink-deep);
  }
  .body code {
    font-family: 'Courier New', monospace;
    font-size: 13px;
    background: var(--surface);
    padding: 1px 6px;
    border-radius: 4px;
    color: var(--ink-deep);
  }
  .body a {
    color: var(--link);
  }
  .body a:hover {
    color: var(--coral);
  }
</style>
